2. ASPCoreMVC/Models/ApplicationDbContext.cs
using ASPCoreMVC.Models;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace MyWebApp.Models
{
    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }
    }
}

2. ASPCoreMVC/Models/ApplicationUser.cs
using Microsoft.AspNetCore.Identity;

namespace ASPCoreMVC.Models
{
    public class ApplicationUser : IdentityUser
    {
        public string? Nickname {  get; set; }
        public string? UserID {  get; set; }
    }
}

2. ASPCoreMVC/Models/ErrorViewModel.cs
namespace ASPCoreMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

2. ASPCoreMVC/ViewModels/SigninViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ASPCoreMVC.ViewModels
{
    public class SigninViewModel
    {
        [Required(ErrorMessage = "아이디를 입력하세요.")]
        [StringLength(20, MinimumLength = 5, ErrorMessage = "아이디는 5~20자 사이여야 합니다.")]
        public string UserID { get; set; }

        [Required(ErrorMessage = "비밀번호를 입력하세요")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

2. ASPCoreMVC/ViewModels/SignupViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ASPCoreMVC.ViewModels
{
    public class SignupViewModel
    {
        [Required(ErrorMessage = "아이디를 입력하세요.")]
        [StringLength(20, MinimumLength = 5, ErrorMessage = "아이디는 5~20자 사이여야 합니다.")]
        public string UserID { get; set; }

        [Required(ErrorMessage = "비밀번호를 입력하세요.")]
        [DataType(DataType.Password)]
        [MinLength(6, ErrorMessage = "비밀번호는 최소 6자 이상이어야 합니다.")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "비밀번호가 일치하지 않습니다.")]
        public string ConfirmPassword { get; set; }

        [Required(ErrorMessage = "닉네임을 입력하세요.")]
        [MaxLength(50, ErrorMessage = "닉네임은 50자를 초과할 수 없습니다.")]
        public string Nickname { get; set; }
    }
}

2. ASPCoreMVC/Controllers/AccountAPIController.cs
using ASPCoreMVC.Models;
using ASPCoreMVC.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ASPCoreMVC.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class AccountAPIController : Controller
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public AccountAPIController(SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager)
        {
            _signInManager = signInManager;
            _userManager = userManager;
        }

        [HttpPost("login")]
        public async Task<IActionResult> Login([FromBody] SigninViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(model.UserID, model.Password, isPersistent: false, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    var code = Guid.NewGuid().ToString();
                    code = "hello, world!!";
                    return Ok(new { Message = "로그인 성공", Code = code });
                }
                return Unauthorized(new { Message = "아이디 또는 비밀번호가 잘못되었습니다." });
            }
            return BadRequest(ModelState);
        }
    }
}

2. ASPCoreMVC/Controllers/HomeController.cs
using System.Diagnostics;
using ASPCoreMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace ASPCoreMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

2. ASPCoreMVC/Controllers/LoginController.cs
using ASPCoreMVC.Models;
using ASPCoreMVC.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ASPCoreMVC.Controllers
{
    public class LoginController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public LoginController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [HttpGet]
        public IActionResult Signup()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Signup(SignupViewModel model)
        {
            if (ModelState.IsValid)
            {
                var exists = await _userManager.Users
                    .AnyAsync(u => u.UserID == model.UserID);
                if (exists)
                {
                    ModelState.AddModelError("UserID", "이미 사용 중인 ID입니다.");
                    return View(model);
                }

                var user = new ApplicationUser
                {
                    UserID = model.UserID,
                    UserName = model.UserID,
                    Nickname = model.Nickname,
                };

                var result = await _userManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    await _signInManager.SignInAsync(user, isPersistent: false);
                    return RedirectToAction("Index", "Home");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Signout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult Signin()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Signin(SigninViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(model.UserID, model.Password, false, lockoutOnFailure: false);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError(string.Empty, "아이디 또는 비밀번호가 잘못되었습니다.");
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Agree()
        {
            return View();
        }
    }
}

2. ASPCoreMVC/Controllers/MainController.cs
using Microsoft.AspNetCore.Mvc;

namespace ASPCoreMVC.Controllers
{
    public class MainController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

2. ASPCoreMVC/Views/Login/Agree.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>약관</h1>
<p>학생이 만든 학습용 사이트입니다.<br /> 개인정보를 기입하지 마세요.</p>
<p>아이디 비밀번호 예시: temp temp1234</p>
<a class="btn btn-dark" asp-area="" asp-controller="Login" asp-action="Signup">회원가입 하기</a>

2. ASPCoreMVC/Views/Login/Signin.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "로그인";
}
@model ASPCoreMVC.ViewModels.SigninViewModel

<h2>로그인</h2>
<form asp-action="Signin" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="UserID">아이디</label>
        <input asp-for="UserID" class="form-control" />
        <span asp-validation-for="UserID" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Password">비밀번호</label>
        <input asp-for="Password" class="form-control" />
        <span asp-validation-for="Password" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-dark">로그인</button>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

2. ASPCoreMVC/Views/Login/Signup.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "회원가입";
}
@model ASPCoreMVC.ViewModels.SignupViewModel

<h2>회원가입</h2>
<form asp-action="Signup" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="UserID">아이디</label>
        <input asp-for="UserID" class="form-control" />
        <span asp-validation-for="UserID" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Password">비밀번호</label>
        <input asp-for="Password" class="form-control" />
        <span asp-validation-for="Password" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="ConfirmPassword">비밀번호 확인</label>
        <input asp-for="ConfirmPassword" class="form-control" />
        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Nickname">닉네임</label>
        <input asp-for="Nickname" class="form-control" />
        <span asp-validation-for="Nickname" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-dark">가입하기</button>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

2. ASPCoreMVC/Views/Main/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "MainPage";
}

<h1>@ViewData["Title"]</h1>
<p>hello, world!!</p>

2. ASPCoreMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASPCoreMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASPCoreMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Main" asp-action="Index">Main</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav m-auto">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <span class="nav-link text-black">@User.Identity.Name</span>
                            </li>
                            <li class="nav-item">
                                <form asp-area="" asp-controller="Login" asp-action="Signout" method="post">
                                    <button type="submit" class="nav-link btn btn-link text-black">Sign out</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-black" asp-area="" asp-controller="Login" asp-action="Signin">Sign in</a>
                            </li>
                            <li class="nav-item m-auto">
                                <a class="nav-link text-black" asp-area="" asp-controller="Login" asp-action="Agree">Sign up</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - ASPCoreMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>